<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { Refresh } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { api, errorMessage } from '../api/client'

const summary=ref<any>({}), health=ref<any>({}), preflight=ref<any>(null), workers=ref<any[]>([]), limits=ref<any[]>([]), loading=ref(false), updatedAt=ref<Date|null>(null)
const checks=computed(()=>preflight.value?.checks||[])
let refreshTimer:number|undefined
async function load(){if(loading.value)return;loading.value=true;try{const [s,h,p,w,l]=await Promise.all([api<any>('/operations/summary'),api<any>('/health/ready'),api<any>('/operations/preflight'),api<any>('/operations/workers'),api<any>('/operations/rate-limits')]);summary.value=s;health.value=h;preflight.value=p;workers.value=w.workers;limits.value=l.windows;updatedAt.value=new Date()}catch(error:unknown){ElMessage.error(errorMessage(error,'运行状态加载失败'))}finally{loading.value=false}}
onMounted(()=>{load();refreshTimer=window.setInterval(load,30000)})
onUnmounted(()=>window.clearInterval(refreshTimer))
</script>
<template><div class="page" v-loading="loading"><div class="page-heading"><div><h2>运行监控</h2><p>健康、预检、任务容量、Worker 与租户配额的实时视图</p></div><div class="refresh-tools"><small v-if="updatedAt" class="muted">更新于 {{ updatedAt.toLocaleTimeString() }}</small><el-button :icon="Refresh" @click="load">刷新状态</el-button></div></div>
<div class="metric-grid"><div class="metric-card surface"><small>系统健康</small><strong><i :class="['status-dot',health.status==='ok'?'':'fail']"></i>{{ health.status==='ok'?'就绪':'降级' }}</strong><span class="muted">MySQL {{ health.mysql?'已连接':'异常' }} · LLM {{ health.llm?'已配置':'异常' }}</span></div><div class="metric-card surface"><small>答辩预检</small><strong>{{ preflight?.status==='ready'?'可以演示':'需要处理' }}</strong><span class="muted">{{ preflight?.passed||0 }} 通过 · {{ preflight?.warnings||0 }} 提醒</span></div><div class="metric-card surface"><small>任务运行</small><strong>{{ summary.active_tasks||0 }} / {{ summary.worker_capacity||0 }}</strong><span class="muted">排队 {{ summary.queued_tasks||0 }} · {{ summary.execution_mode }}</span></div><div class="metric-card surface"><small>模型调用 / Token</small><strong>{{ summary.usage?.llm_calls||0 }} / {{ summary.usage?.total_tokens||0 }}</strong><span class="muted">失败 {{ summary.usage?.llm_failures||0 }} · 估算 ${{ (summary.usage?.estimated_cost_usd||0).toFixed(4) }}</span></div><div class="metric-card surface"><small>可追溯事件</small><strong>{{ summary.event_count||0 }}</strong><span class="muted">检查点 {{ summary.checkpoint_count||0 }} · 审计 {{ summary.audit_event_count||0 }}</span></div></div>
<div class="surface preflight"><div class="table-header"><h3>答辩预检清单</h3><el-tag :type="preflight?.status==='ready'?'success':'danger'">{{ preflight?.status }}</el-tag></div><div class="check-grid"><div v-for="check in checks" :key="check.key" :class="['check',check.status]"><b>{{ check.status==='pass'?'✓':check.status==='warning'?'!':'×' }}</b><div><strong>{{ check.label }}<small v-if="!check.critical"> · 建议项</small></strong><span>{{ check.detail }}</span></div></div></div></div>
<h3 class="section">多智能体执行链路</h3><div class="agent-flow"><div v-for="(item,index) in ['需求规划','Schema 检索','SQL 生成执行','数据治理','分析预测','报告生成','图表渲染']" :key="item"><small>0{{index+1}}</small><strong>{{item}}</strong><span v-if="index<6">→</span></div></div>
<div class="ops-columns"><div class="surface"><div class="table-header"><h3>Worker 状态</h3><span class="muted">{{ workers.length }} 在线</span></div><el-table :data="workers" empty-text="内嵌模式，无独立 Worker"><el-table-column prop="worker_id" label="Worker"/><el-table-column prop="status" label="状态"/><el-table-column prop="current_task_id" label="当前任务"/></el-table></div><div class="surface"><div class="table-header"><h3>租户配额</h3><span class="muted">当前窗口</span></div><el-table :data="limits" empty-text="当前窗口暂无请求"><el-table-column prop="owner_id" label="租户"/><el-table-column prop="request_count" label="已用" width="90"/><el-table-column prop="remaining" label="剩余" width="90"/></el-table></div></div></div></template>
<style scoped>.preflight{overflow:hidden}.check-grid{display:grid;grid-template-columns:1fr 1fr;padding:5px 18px 15px;gap:0 25px}.check{display:flex;gap:10px;padding:12px 0;border-bottom:1px solid var(--border)}.check>b{color:#22c55e}.check.warning>b{color:#f59e0b}.check.fail>b{color:#ef4444}.check strong,.check span{display:block;font-size:13px}.check span{font-size:11px;color:#8993a5;margin-top:4px}.check small{color:#f59e0b}.section{margin:23px 0 13px;font-size:16px}.agent-flow{display:grid;grid-template-columns:repeat(7,1fr);gap:9px}.agent-flow>div{position:relative;padding:16px 10px;background:#fff;border:1px solid #dfe5f0;border-radius:11px;text-align:center}.agent-flow small,.agent-flow strong{display:block}.agent-flow small{color:#8190ee}.agent-flow strong{font-size:12px;margin-top:5px}.agent-flow span{position:absolute;right:-8px;top:20px;color:#aab2c0;z-index:2}.ops-columns{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:20px}.ops-columns>.surface{overflow:hidden}</style>
