<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { Refresh, View, RefreshRight } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { ElMessageBox } from 'element-plus'
import { useRoute } from 'vue-router'
import { api, errorMessage } from '../api/client'
import type { Task } from '../types'
import ResultVisuals from '../components/ResultVisuals.vue'
import StructuredReport from '../components/StructuredReport.vue'

const tasks=ref<Task[]>([]), loading=ref(false), status=ref(''), drawer=ref(false), selected=ref<Task|null>(null)
const route=useRoute()
const labels:Record<string,string>={queued:'排队中',running:'执行中',waiting_clarification:'等待澄清',cancelling:'取消中',completed:'已完成',failed:'失败',cancelled:'已取消',interrupted:'已中断'}
const tagType=(s:string)=>s==='completed'?'success':s==='failed'||s==='interrupted'?'danger':s==='running'?'warning':'info'
let refreshTimer:number|undefined
async function load(){if(loading.value)return;loading.value=true;try{const q=status.value?`?limit=100&status=${status.value}`:'?limit=100';tasks.value=(await api<{tasks:Task[]}>(`/tasks${q}`)).tasks}catch(error:unknown){ElMessage.error(errorMessage(error,'任务列表加载失败'))}finally{loading.value=false}}
async function detail(task:Task){try{selected.value=await api<Task>(`/tasks/${task.task_id}`);drawer.value=true}catch(error:unknown){ElMessage.error(errorMessage(error,'任务详情加载失败'))}}
async function retry(task:Task){try{await ElMessageBox.confirm('从头重试会再次执行模型调用、只读 SQL 和分析步骤，可能产生重复计费。检查点继续当前因幂等风险被禁用。','确认从头重试',{type:'warning',confirmButtonText:'创建重试任务',cancelButtonText:'取消'});await api(`/tasks/${task.task_id}/retry?mode=restart`,{method:'POST'});ElMessage.success('已创建从头重试任务');load()}catch(error:unknown){if(error!=='cancel'&&error!=='close')ElMessage.error(errorMessage(error,'任务重试失败'))}}
async function cancel(task:Task){try{await ElMessageBox.confirm('取消将在安全边界生效，当前数据库或模型调用可能会先结束。','确认取消任务',{type:'warning',confirmButtonText:'取消任务',cancelButtonText:'返回'});await api(`/tasks/${task.task_id}`,{method:'DELETE'});ElMessage.success('已提交取消请求');load()}catch(error:unknown){if(error!=='cancel'&&error!=='close')ElMessage.error(errorMessage(error,'任务取消失败'))}}
onMounted(async()=>{await load();const taskId=Array.isArray(route.query.task)?route.query.task[0]:route.query.task;if(taskId)await detail({task_id:taskId} as Task);refreshTimer=window.setInterval(()=>{if(tasks.value.some(task=>['queued','running','waiting_clarification','cancelling'].includes(task.status)))load()},5000)})
onUnmounted(()=>window.clearInterval(refreshTimer))
</script>
<template><div class="page"><div class="page-heading"><div><h2>任务中心</h2><p>查看异步分析任务、运行状态、结果和失败恢复</p></div><el-button :icon="Refresh" @click="load">刷新</el-button></div><div class="surface"><div class="task-filter"><el-select v-model="status" placeholder="全部状态" clearable style="width:180px" @change="load"><el-option v-for="(label,key) in labels" :key="key" :label="label" :value="key"/></el-select><span class="muted">共 {{ tasks.length }} 条任务</span></div><el-table v-loading="loading" :data="tasks" stripe><el-table-column prop="query" label="分析问题" min-width="320" show-overflow-tooltip/><el-table-column prop="intent" label="意图" width="120"/><el-table-column label="状态" width="110"><template #default="scope"><el-tag :type="tagType(scope.row.status)" size="small">{{ labels[scope.row.status]||scope.row.status }}</el-tag></template></el-table-column><el-table-column label="创建时间" width="180"><template #default="scope">{{ new Date(scope.row.created_at*1000).toLocaleString() }}</template></el-table-column><el-table-column label="耗时" width="100"><template #default="scope">{{ (scope.row.updated_at-scope.row.created_at).toFixed(1) }}s</template></el-table-column><el-table-column label="操作" width="210" fixed="right"><template #default="scope"><el-button link type="primary" :icon="View" @click="detail(scope.row)">详情</el-button><el-button v-if="['queued','running','waiting_clarification','cancelling'].includes(scope.row.status)" link type="danger" @click="cancel(scope.row)">取消</el-button><el-button v-if="['failed','cancelled','interrupted'].includes(scope.row.status)" link :icon="RefreshRight" @click="retry(scope.row)">重试</el-button></template></el-table-column></el-table></div>
<el-drawer v-model="drawer" title="任务详情" size="72%"><template v-if="selected"><el-descriptions :column="2" border><el-descriptions-item label="任务 ID"><code>{{ selected.task_id }}</code></el-descriptions-item><el-descriptions-item label="状态"><el-tag :type="tagType(selected.status)">{{ labels[selected.status] }}</el-tag></el-descriptions-item><el-descriptions-item label="结果模式"><el-tag :type="selected.result?.result_mode==='cached_demo'?'warning':'success'">{{ selected.result?.result_mode==='cached_demo'?'缓存演示':'实时 Agent' }}</el-tag></el-descriptions-item><el-descriptions-item label="Trace ID"><code>{{ selected.trace_id||selected.task_id }}</code></el-descriptions-item><el-descriptions-item label="意图">{{ selected.intent||'自动识别' }}</el-descriptions-item><el-descriptions-item label="创建时间">{{ new Date(selected.created_at*1000).toLocaleString() }}</el-descriptions-item><el-descriptions-item v-if="selected.parent_task_id" label="重试来源"><code>{{ selected.parent_task_id }}</code> · {{ selected.retry_mode }}</el-descriptions-item><el-descriptions-item label="问题" :span="2">{{ selected.query }}</el-descriptions-item></el-descriptions><el-alert v-if="selected.retry_risks?.length" title="该任务是从头重试：模型、只读 SQL 与分析步骤可能重复执行和计费。" type="warning" show-icon :closable="false"/><template v-if="selected.result"><h3>分析报告</h3><div class="report"><StructuredReport :content="selected.result.report||'该任务未生成文本报告'" /></div><ResultVisuals :result="selected.result"/><h3>生成 SQL</h3><pre>{{ selected.result.sql||'无' }}</pre></template><el-alert v-if="selected.error" :title="selected.error" type="error" show-icon :closable="false" /></template></el-drawer></div></template>
<style scoped>.task-filter{padding:14px 18px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--border)}pre{padding:14px;background:#101827;color:#d6e0f0;border-radius:9px;white-space:pre-wrap}.report{padding:16px;background:#f7f9fc;border-radius:9px}</style>
